# Prática Independente de Pandas 1 - SOLUÇÃO.

### 1. Introdução.

#### Diariamente, o Ministério da Saúde, por meio da Secretaria de Vigilância em Saúde (SVS/MS) divulga dados consolidados sobre o [COVID-19](https://covid.saude.gov.br/). Acesso o arquivo "`HIST_PAINEL_COVIDBR_20mai2020.xlsx`" e responda às questões a seguir.

#### Importamos os pacotes a serem usados.

In [46]:
import pandas as pd
import numpy as np

#### Importamos os dados a serem usados.

In [51]:
covid19Brasil = pd.read_excel("HIST_PAINEL_COVIDBR_20mai2020.xlsx", encoding = 'UTF-8')
#covid19Brasil = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv',sep = ',')

In [53]:
#covid19Brasil
covid19SP.index

Int64Index([57883, 57884, 57885, 57886, 57887, 57888, 57889, 57890, 57891,
            57892,
            ...
            72113, 72114, 72115, 72116, 72117, 72118, 72119, 72120, 72121,
            72122],
           dtype='int64', length=14240)

#### Exercício 1.1: Faça um slice no dataframe para considerar apenas os dados do estado de São Paulo.

In [26]:
covid19SP = covid19Brasil.loc[(covid19Brasil['regiao'] == 'Sudeste') 
                              & (covid19Brasil['estado'] == 'SP')
                              & (covid19Brasil['municipio'].notna())
                             ]
covid19SP.head(100)
#covid19Brasil.municipio.loc[(covid19Brasil.regiao == 'Sudeste') & (covid19Brasil.estado == 'SP')]
#covid19Brasil.iloc[2,7]

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,obitosAcumulado,Recuperadosnovos,emAcompanhamentoNovos
57883,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-03,14,35068.0,1,0,NaN,NaN
57884,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-04,14,35068.0,1,0,NaN,NaN
57885,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-14,16,35068.0,1,0,NaN,NaN
57886,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-15,16,35068.0,1,0,NaN,NaN
57887,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-16,16,35068.0,1,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57978,Sudeste,SP,Águas da Prata,35,350040.0,35142.0,Mantiqueira,2020-05-07,19,8180.0,1,0,NaN,NaN
57979,Sudeste,SP,Águas da Prata,35,350040.0,35142.0,Mantiqueira,2020-05-08,19,8180.0,1,0,NaN,NaN
57980,Sudeste,SP,Águas da Prata,35,350040.0,35142.0,Mantiqueira,2020-05-09,19,8180.0,1,0,NaN,NaN
57981,Sudeste,SP,Águas da Prata,35,350040.0,35142.0,Mantiqueira,2020-05-10,20,8180.0,1,0,NaN,NaN
57982,Sudeste,SP,Águas da Prata,35,350040.0,35142.0,Mantiqueira,2020-05-11,20,8180.0,1,0,NaN,NaN

#### Exercício 1.2: Selecione também um dataset contendo apenas os dados para a capital de SP.

In [28]:
covid19SPCapital = covid19Brasil.loc[(covid19Brasil['regiao'] == 'Sudeste') 
                                   & (covid19Brasil['estado'] == 'SP')
                                   & (covid19Brasil['municipio'] == 'São Paulo')                              
                                  ]

covid19SPCapital.head(100)

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,obitosAcumulado,Recuperadosnovos,emAcompanhamentoNovos
70206,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-03-28,13,12252023.0,1149,76,NaN,NaN
70207,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-03-29,14,12252023.0,1183,89,NaN,NaN
70208,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-03-30,14,12252023.0,1233,103,NaN,NaN
70209,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-03-31,14,12252023.0,1885,121,NaN,NaN
70210,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-01,14,12252023.0,2418,144,NaN,NaN
70211,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-02,14,12252023.0,2815,164,NaN,NaN
70212,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-03,14,12252023.0,3202,186,NaN,NaN
70213,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-04,14,12252023.0,3496,212,NaN,NaN
70214,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-05,15,12252023.0,3612,220,NaN,NaN
70215,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-06,15,12252023.0,3754,244,NaN,NaN
70216,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-07,15,12252023.0,4258,296,NaN,NaN
70217,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-08,15,12252023.0,4946,339,NaN,NaN
70218,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-09,15,12252023.0,5477,384,NaN,NaN
70219,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-10,15,12252023.0,5982,409,NaN,NaN
70220,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-11,15,12252023.0,6131,422,NaN,NaN
70221,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-12,16,12252023.0,6352,445,NaN,NaN
70222,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-13,16,12252023.0,6418,456,NaN,NaN
70223,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-14,16,12252023.0,6705,512,NaN,NaN
70224,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-15,16,12252023.0,7764,558,NaN,NaN
70225,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-16,16,12252023.0,7908,603,NaN,NaN
70226,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-17,16,12252023.0,8744,643,NaN,NaN
70227,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-18,16,12252023.0,9428,686,NaN,NaN
70228,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-19,17,12252023.0,9668,700,NaN,NaN
70229,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-20,17,12252023.0,9815,715,NaN,NaN
70230,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-21,17,12252023.0,10342,753,NaN,NaN
70231,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-22,17,12252023.0,10691,778,NaN,NaN
70232,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-23,17,12252023.0,11225,912,NaN,NaN
70233,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-24,17,12252023.0,11800,1010,NaN,NaN
70234,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-25,17,12252023.0,13098,1099,NaN,NaN
70235,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-26,18,12252023.0,13513,1114,NaN,NaN
70236,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-27,18,12252023.0,13989,1172,NaN,NaN
70237,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-28,18,12252023.0,15397,1321,NaN,NaN
70238,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-29,18,12252023.0,16638,1439,NaN,NaN
70239,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-04-30,18,12252023.0,18149,1522,NaN,NaN
70240,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-01,18,12252023.0,19087,1607,NaN,NaN
70241,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-02,18,12252023.0,19494,1661,NaN,NaN
70242,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-03,19,12252023.0,19822,1673,NaN,NaN
70243,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-04,19,12252023.0,20073,1683,NaN,NaN
70244,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-05,19,12252023.0,21140,1801,NaN,NaN
70245,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-06,19,12252023.0,23187,1910,NaN,NaN
70246,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-07,19,12252023.0,24273,1986,NaN,NaN
70247,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-08,19,12252023.0,25366,2110,NaN,NaN
70248,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-09,19,12252023.0,26787,2223,NaN,NaN
70249,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-10,20,12252023.0,27307,2266,NaN,NaN
70250,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-11,20,12252023.0,27771,2283,NaN,NaN
70251,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-12,20,12252023.0,28682,2407,NaN,NaN
70252,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-13,20,12252023.0,30402,2496,NaN,NaN
70253,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-14,20,12252023.0,31873,2596,NaN,NaN
70254,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-15,20,12252023.0,33992,2674,NaN,NaN
70255,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-16,20,12252023.0,35429,2792,NaN,NaN
70256,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-17,21,12252023.0,35931,2835,NaN,NaN
70257,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-18,21,12252023.0,36188,2856,NaN,NaN
70258,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-19,21,12252023.0,37640,3029,NaN,NaN
70259,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,2020-05-20,21,12252023.0,39466,3135,NaN,NaN

### 2. Explorando o dataset.

#### Exercício 2.1. Quantas filas e quantas colunas o dataset tem?

In [57]:
covid19SP.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14240 entries, 57883 to 72122
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   regiao                 14240 non-null  object
 1   estado                 14240 non-null  object
 2   municipio              14240 non-null  object
 3   coduf                  14240 non-null  int64
 4   codmun                 14240 non-null  float64
 5   codRegiaoSaude         14240 non-null  float64
 6   nomeRegiaoSaude        14240 non-null  object
 7   data                   14240 non-null  object
 8   semanaEpi              14240 non-null  int64
 9   populacaoTCU2019       14240 non-null  float64
 10  casosAcumulado         14240 non-null  int64
 11  obitosAcumulado        14240 non-null  int64
 12  Recuperadosnovos       0 non-null      float64
 13  emAcompanhamentoNovos  0 non-null      float64
dtypes: float64(5), int64(4), object(5)
memory usage: 1.6+ MB

#### Exercício 2.2 Que informação o dataset tem? Imprima o nome das colunas.

In [30]:
covid19SP.columns

Index(['regiao', 'estado', 'municipio', 'coduf', 'codmun', 'codRegiaoSaude',
       'nomeRegiaoSaude', 'data', 'semanaEpi', 'populacaoTCU2019',
       'casosAcumulado', 'obitosAcumulado', 'Recuperadosnovos',
       'emAcompanhamentoNovos'],
      dtype='object')

#### Exercício 2.3: Como o dataset está indexado?

In [31]:
covid19SP.index

Int64Index([57883, 57884, 57885, 57886, 57887, 57888, 57889, 57890, 57891,
            57892,
            ...
            72113, 72114, 72115, 72116, 72117, 72118, 72119, 72120, 72121,
            72122],
           dtype='int64', length=14240)

#### Exercício 2.4: Qual é o tipo da quarta coluna?

In [32]:
covid19SP.iloc[:,3].dtype

dtype('int64')

#### Exercício 2.5: Qual é o município com o maior número de instâncias no dataset?

In [33]:
covid19SP['municipio'].value_counts().head(100)

Arujá                   54
Mauá                    54
Santo André             54
Suzano                  54
Louveira                54
                        ..
Orlândia                47
Itapetininga            46
Terra Roxa              46
Presidente Venceslau    45
Boituva                 45
Name: municipio, Length: 100, dtype: int64

#### Exercício 2.6: Como os nomes das regiões de saúde estão distribuídos no dataset?

In [34]:
covid19SP['nomeRegiaoSaude'].value_counts()

Região Metropolitana de Campinas    799
Sorocaba                            702
Alto do Tietê                       525
Bauru                               520
Vale do Ribeira                     448
                                   ...
Três Colinas                         66
São Paulo                            54
Jales                                43
Santa Fé do Sul                      32
Pontal do Paranapanema               15
Name: nomeRegiaoSaude, Length: 63, dtype: int64

#### Exercício 2.7: Qual é o número de casos acumulados na capital de SP, no dia 2020-03-31?

In [36]:
covid19SPCapital['casosAcumulado'][(covid19SPCapital['data'] == '2020-03-31')]

70209    1885
Name: casosAcumulado, dtype: int64

#### Exercício 2.8: Qual é o número total de casos acumulados para todas as cidades do estado de SP, no dia 2020-03-31?

In [37]:
covid19SP['casosAcumulado'][(covid19SP['data'] == '2020-03-31')].sum()

2286

#### Exercício 2.9: Qual é o valor médio de "semanaEpi"  durante todo o período?

In [38]:
covid19SP['semanaEpi'].mean()

18.340379213483146

In [39]:
covid19SP.head()

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,obitosAcumulado,Recuperadosnovos,emAcompanhamentoNovos
57883,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-03,14,35068.0,1,0,NaN,NaN
57884,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-04,14,35068.0,1,0,NaN,NaN
57885,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-14,16,35068.0,1,0,NaN,NaN
57886,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-15,16,35068.0,1,0,NaN,NaN
57887,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,2020-04-16,16,35068.0,1,0,NaN,NaN

### 3. Indexando e organizando os dados.

#### Exercício 3.1:  Selecionar  valores não duplicados para as coluna 'municipio','coduf', 'codmun', 'codRegiaoSaude' e atribuí-las a um objeto novo chamado 'covid19SPMunicipios'.

In [40]:
covid19SPMunicipios = covid19SP.drop_duplicates(['municipio','coduf', 'codmun', 'codRegiaoSaude','populacaoTCU2019'])
covid19SPMunicipios = covid19SPMunicipios.drop(['semanaEpi', 'data', 'casosAcumulado', 'obitosAcumulado', 'Recuperadosnovos', 'emAcompanhamentoNovos'], axis = 1)
covid19SPMunicipios

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019
57883,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,35068.0
57922,Sudeste,SP,Adolfo,35,350020.0,35156.0,José Bonifácio,3562.0
57943,Sudeste,SP,Aguaí,35,350030.0,35142.0,Mantiqueira,36305.0
57970,Sudeste,SP,Águas da Prata,35,350040.0,35142.0,Mantiqueira,8180.0
57992,Sudeste,SP,Águas de Lindóia,35,350050.0,35074.0,Circuito das Águas,18705.0
...,...,...,...,...,...,...,...,...
71921,Sudeste,SP,Vista Alegre do Alto,35,355690.0,35052.0,Sul - Barretos,8810.0
71951,Sudeste,SP,Votorantim,35,355700.0,35163.0,Sorocaba,122480.0
72002,Sudeste,SP,Votuporanga,35,355710.0,35157.0,Votuporanga,94547.0
72053,Sudeste,SP,Chavantes,35,355720.0,35094.0,Ourinhos,12418.0
72083,Sudeste,SP,Estiva Gerbi,35,355730.0,35141.0,Baixa Mogiana,11304.0

#### Exercício 3.2:  Selecionar as primeiras 20 filas de 'covid19SPMunicipios'

In [41]:
covid19SPMunicipios[0:20]

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019
57883,Sudeste,SP,Adamantina,35,350010.0,35091.0,Adamantina,35068.0
57922,Sudeste,SP,Adolfo,35,350020.0,35156.0,José Bonifácio,3562.0
57943,Sudeste,SP,Aguaí,35,350030.0,35142.0,Mantiqueira,36305.0
57970,Sudeste,SP,Águas da Prata,35,350040.0,35142.0,Mantiqueira,8180.0
57992,Sudeste,SP,Águas de Lindóia,35,350050.0,35074.0,Circuito das Águas,18705.0
58041,Sudeste,SP,Águas de Santa Bárbara,35,350055.0,35061.0,Vale do Jurumirim,6075.0
58054,Sudeste,SP,Águas de São Pedro,35,350060.0,35103.0,Piracicaba,3451.0
58095,Sudeste,SP,Agudos,35,350070.0,35062.0,Bauru,37214.0
58144,Sudeste,SP,Alambari,35,350075.0,35161.0,Itapetininga,6025.0
58179,Sudeste,SP,Alfredo Marcondes,35,350080.0,35112.0,Alta Sorocabana,4166.0
58181,Sudeste,SP,Altair,35,350090.0,35051.0,Norte - Barretos,4160.0
58186,Sudeste,SP,Altinópolis,35,350100.0,35133.0,Vale das Cachoeiras,16184.0
58194,Sudeste,SP,Alto Alegre,35,350110.0,35023.0,Consórcios do DRS II,4099.0
58206,Sudeste,SP,Alumínio,35,350115.0,35163.0,Sorocaba,18628.0
58215,Sudeste,SP,Álvares Machado,35,350130.0,35112.0,Alta Sorocabana,24915.0
58238,Sudeste,SP,Álvaro de Carvalho,35,350140.0,35093.0,Marília,5227.0
58251,Sudeste,SP,Americana,35,350160.0,35072.0,Região Metropolitana de Campinas,239597.0
58302,Sudeste,SP,Américo Brasiliense,35,350170.0,35031.0,Central do DRS III,40504.0
58342,Sudeste,SP,Américo de Campos,35,350180.0,35157.0,Votuporanga,5969.0
58356,Sudeste,SP,Amparo,35,350190.0,35074.0,Circuito das Águas,72195.0

#### Exercício 3.3:  Selecionar uma amostra aleatória de 100 filas de 'covid19SPMunicipios'

In [42]:
covid19SPMunicipios.sample(100)

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019
59541,Sudeste,SP,Bebedouro,35,350610.0,35052.0,Sul - Barretos,77496.0
63397,Sudeste,SP,Itajobi,35,352190.0,35151.0,Catanduva,15262.0
66745,Sudeste,SP,Pardinho,35,353610.0,35063.0,Polo Cuesta,6435.0
61945,Sudeste,SP,Ferraz de Vasconcelos,35,351570.0,35011.0,Alto do Tietê,194276.0
57922,Sudeste,SP,Adolfo,35,350020.0,35156.0,José Bonifácio,3562.0
...,...,...,...,...,...,...,...,...
66079,Sudeste,SP,Monte Mor,35,353180.0,35072.0,Região Metropolitana de Campinas,59772.0
67656,Sudeste,SP,Pitangueiras,35,353950.0,35131.0,Horizonte Verde,39719.0
68798,Sudeste,SP,Salesópolis,35,354500.0,35011.0,Alto do Tietê,17139.0
69665,Sudeste,SP,São Bento do Sapucaí,35,354860.0,35174.0,Vale do Paraíba/Região Serrana,10878.0
68789,Sudeste,SP,Sagres,35,354470.0,35091.0,Adamantina,2432.0

#### Exercício 3.4: Escolher todas as colunas, exceto `coduf`. Utilize a propriedade columns para filtrar na dimensão das colunas.

In [43]:
covid19SPMunicipios.loc[:,covid19SPMunicipios.columns != 'coduf']

,regiao,estado,municipio,codmun,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019
57883,Sudeste,SP,Adamantina,350010.0,35091.0,Adamantina,35068.0
57922,Sudeste,SP,Adolfo,350020.0,35156.0,José Bonifácio,3562.0
57943,Sudeste,SP,Aguaí,350030.0,35142.0,Mantiqueira,36305.0
57970,Sudeste,SP,Águas da Prata,350040.0,35142.0,Mantiqueira,8180.0
57992,Sudeste,SP,Águas de Lindóia,350050.0,35074.0,Circuito das Águas,18705.0
...,...,...,...,...,...,...,...
71921,Sudeste,SP,Vista Alegre do Alto,355690.0,35052.0,Sul - Barretos,8810.0
71951,Sudeste,SP,Votorantim,355700.0,35163.0,Sorocaba,122480.0
72002,Sudeste,SP,Votuporanga,355710.0,35157.0,Votuporanga,94547.0
72053,Sudeste,SP,Chavantes,355720.0,35094.0,Ourinhos,12418.0
72083,Sudeste,SP,Estiva Gerbi,355730.0,35141.0,Baixa Mogiana,11304.0

#### Exercício 3.5: Organizar o dataset dos municípios segundo a população, de forma decrescente.

In [44]:
covid19SPMunicipios.sort_values(['populacaoTCU2019'], ascending = False)

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019
70206,Sudeste,SP,São Paulo,35,355030.0,35016.0,São Paulo,12252023.0
62581,Sudeste,SP,Guarulhos,35,351880.0,35011.0,Alto do Tietê,1379182.0
60464,Sudeste,SP,Campinas,35,350950.0,35072.0,Região Metropolitana de Campinas,1204073.0
69671,Sudeste,SP,São Bernardo do Campo,35,354870.0,35015.0,Grande ABC,838936.0
70021,Sudeste,SP,São José dos Campos,35,354990.0,35171.0,Alto Vale do Paraíba,721944.0
...,...,...,...,...,...,...,...,...
62356,Sudeste,SP,Guarani d'Oeste,35,351800.0,35154.0,Fernandópolis,2000.0
71617,Sudeste,SP,União Paulista,35,355570.0,35156.0,José Bonifácio,1844.0
66883,Sudeste,SP,Paulistânia,35,353657.0,35062.0,Bauru,1833.0
71447,Sudeste,SP,Trabiju,35,355475.0,35031.0,Central do DRS III,1724.0
71631,Sudeste,SP,Uru,35,355590.0,35065.0,Lins,1165.0

#### Exercício 3.6: Qual é a população média da população dos municípios, despois de excluirmos aqueles cujas populações são menores que 10000000 e maiores que 500000 habitantes?

In [45]:
covid19SPMunicipios['populacaoTCU2019'][(covid19SPMunicipios['populacaoTCU2019'] >= 500000.0) & 
                                      (covid19SPMunicipios['populacaoTCU2019'] <= 10000000.0) 
                                       ].mean()

867999.625